.IGNORE: default run

build:
	docker build -t adambene/react-native-android .

run:
	docker run --rm -it adambene/react-native-android bash

push:
	docker push adambene/react-native-android

default: build
